"""Copy the plugin's shaders and constants into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the generated block of demo/plugin.js
    python3 demo/tools/sync_shaders.py --print  print the block instead

`demo/plugin.js` carries one region between the lines

    //=== BEGIN GENERATED by demo/tools/sync_shaders.py
    //=== END GENERATED

and this script owns it. Everything in it is text lifted out of the C++:

  - the seven GLSL strings of `source/Shaders.cpp` -- the vertex body, the
    `kModel` library and the capture, meter, develop, resample and print
    bodies -- each spliced into a JavaScript template literal with its tabs,
    its comments and its blank lines exactly as they are, plus the version line
    `assemble` prepends. A template literal cannot hold a raw backtick, a
    backslash or a `${`, so those three are escaped (none occurs today) and
    `check_shaders.py` undoes exactly those three and refuses any other escape;
  - `K_CONSTANTS`, the constants block that `constants()` in Shaders.cpp writes
    from Model.h at run time. It is the SAME TEXT: every `put( "name", expr )`
    line of `constants()` is read out of Shaders.cpp, its expression evaluated
    from Model.h's numbers (a `float` constant rounded to binary32 first, as the
    C++ promotes the float and not the decimal; `std::exp2` as exp2), and
    printed with C's `%.9g`, which Python's `%` formatting is. `check_shaders.py
    --dump DIR` compares the whole assembled text with what the plugin itself
    compiles (`intest --dump-shaders DIR`), so this cannot drift unseen;
  - every constant of `source/Model.h` the CPU half reads (scalars and arrays,
    a `float` through Math.fround, an expression such as kStopActivation
    evaluated by JavaScript in double, as the compiler does), the stocks, and
    the option counts and names of `source/Controls.h` / `Controls.cpp`.

What this script does NOT write is the port: every control's law in
Controls.cpp, PrintLayout, ArrheniusFactor, and Instant::ProcessOpenGL's clock,
take, buffers, resize resample, stock arithmetic and uniforms are a hand
translation in plugin.js, and only a reader checks those.

Run it whenever a shader or a constant changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import math
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PLUGIN_JS = os.path.join(REPO, "demo", "plugin.js")

BEGIN = "//=== BEGIN GENERATED by demo/tools/sync_shaders.py"
END = "//=== END GENERATED"

# JS constant, C++ symbol in source/Shaders.cpp. Order is the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("MODEL", "kModel"),
    ("CAPTURE_BODY", "kCaptureBody"),
    ("METER_BODY", "kMeterBody"),
    ("DEVELOP_BODY", "kDevelopBody"),
    ("RESAMPLE_BODY", "kResampleBody"),
    ("PRINT_BODY", "kPrintBody"),
]

# The stages the plugin compiles, as intest --dump-shaders names them: the
# body, and whether `assemble` puts the constants and the model in front.
# Shaders.cpp's Vertex() / Capture() / ... functions, read as data.
STAGES = [
    ("vertex.vert", "VERTEX_BODY", False),
    ("capture.frag", "CAPTURE_BODY", True),
    ("meter.frag", "METER_BODY", True),
    ("develop.frag", "DEVELOP_BODY", True),
    ("resample.frag", "RESAMPLE_BODY", False),
    ("print.frag", "PRINT_BODY", True),
]


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)\\n";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def number(token):
    """A C++ numeric literal as JavaScript: drop a float's f suffix, nothing else."""
    token = token.strip()
    return re.sub(r"(?<=[0-9.])f\b", "", token)


def to_float32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def model_values(model_h):
    """Model.h's scalars and arrays as Python numbers, with their C++ types."""
    values = {}
    for match in re.finditer(r"constexpr (double|float|int) (k\w+)\s*=\s*([^;{\[]+);", model_h):
        kind, name, expr = match.group(1), match.group(2), match.group(3)
        value = eval(number(expr), {}, dict(values))  # names already seen, in file order
        values[name] = to_float32(value) if kind == "float" else value
    for match in re.finditer(r"constexpr (double|float) (k\w+)\[ \d+ \]\s*=\s*\{([^}]*)\};", model_h):
        kind, name, body = match.group(1), match.group(2), match.group(3)
        items = [float(number(t)) for t in body.split(",") if t.strip()]
        values[name] = [to_float32(v) for v in items] if kind == "float" else items
    return values


def constants_block(shaders_cpp, model_h):
    """What Shaders.cpp's constants() writes, line for line."""
    body = re.search(r"std::string constants\(\)\s*\{(.*?)\n\treturn s;", shaders_cpp, re.S)
    if body is None:
        raise SystemExit("constants() not found in source/Shaders.cpp")
    fmt = re.search(r'"(const float %s = %[^"]*);\\n"', body.group(1))
    if fmt is None:
        raise SystemExit("constants()'s format string not found in source/Shaders.cpp")
    values = model_values(model_h)
    lines = []
    for match in re.finditer(r'put\( "(\w+)", (.*?) \);', body.group(1)):
        name, expr = match.group(1), match.group(2)
        py = re.sub(r"m::(k\w+)\[ (\d+) \]", r"\1[\2]", expr)
        py = re.sub(r"m::(k\w+)", r"\1", py)
        py = py.replace("std::exp2", "exp2")
        value = eval(py, {"exp2": lambda x: math.ldexp(1.0, int(x)) if float(x).is_integer() else 2.0 ** x}, values)
        lines.append((fmt.group(1) % (name, float(value))) + ";\n")
    if not lines:
        raise SystemExit("constants() puts nothing?")
    return "".join(lines)


def js_scalars(source, types, prefix):
    """`constexpr T kName = expr;` -> (name, JavaScript expression), in file order."""
    out = []
    for match in re.finditer(r"constexpr (" + types + r") (k\w+)\s*=\s*([^;{\[]+);", source):
        kind, name, expr = match.group(1), match.group(2), match.group(3)
        expr = re.sub(r"\s+", " ", number(expr))
        expr = re.sub(r"\b(k\w+)\b", prefix + r".\1", expr)
        if kind == "float":
            expr = f"Math.fround({expr})"
        out.append((name, expr))
    return out


def js_arrays(source, prefix):
    out = []
    for match in re.finditer(r"constexpr (double|float) (k\w+)\[ \d+ \]\s*=\s*\{([^}]*)\};", source):
        kind, name, body = match.group(1), match.group(2), match.group(3)
        items = [number(t) for t in body.split(",") if t.strip()]
        if kind == "float":
            items = [f"Math.fround({t})" for t in items]
        out.append((name, "[" + ", ".join(items) + "]"))
    return out


def js_stocks(model_h):
    match = re.search(r"constexpr Stock kStocks\[ 3 \] = \{(.*?)\n\};", model_h, re.S)
    if match is None:
        raise SystemExit("kStocks not found in source/Model.h")
    rows = []
    for row in re.finditer(r"\{ ([-0-9.]+), ([-0-9.]+), \{ ([^}]*) \}, \{ ([^}]*) \}, (true|false) \}", match.group(1)):
        shoulder, latitude, dmin, dmax, mono = row.groups()
        rows.append(f"  {{ shoulder: {shoulder}, latitude: {latitude}, dmin: [{dmin}], dmax: [{dmax}], mono: {mono} }},")
    if len(rows) != 3:
        raise SystemExit(f"kStocks: read {len(rows)} rows, not 3")
    return rows


def names_of(controls_cpp, function):
    match = re.search(function + r"\( int index \)\s*\{\s*static const char\* const names\[ \w+ \] = \{ (.*?) \};", controls_cpp, re.S)
    if match is None:
        raise SystemExit(f"{function}'s names not found in source/Controls.cpp")
    return re.findall(r'"([^"]*)"', match.group(1))


def assignments(name, pairs):
    lines = [f"const {name} = {{}};"]
    for key, expr in pairs:
        lines.append(f"{name}.{key} = {expr};")
    return lines


def block():
    shaders_cpp = read("source/Shaders.cpp")
    model_h = read("source/Model.h")
    controls_h = read("source/Controls.h")
    controls_cpp = read("source/Controls.cpp")

    out = [BEGIN + " from source/ -- do not edit by hand.", ""]
    out.append("// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.")
    out.append(f'const K_VERSION = "{cpp_version(shaders_cpp)}";')
    out.append("")
    out.append("// What Shaders.cpp's constants() writes from Model.h at run time, the same text.")
    out.append(f"const K_CONSTANTS = `{escape_template(constants_block(shaders_cpp, model_h))}`;")
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")

    out.append("// source/Model.h: every number of the print.")
    out.extend(assignments("MODEL_H", js_scalars(model_h, "double|float|int", "MODEL_H") + js_arrays(model_h, "MODEL_H")))
    out.append("MODEL_H.kStocks = [")
    out.extend(js_stocks(model_h))
    out.append("];")
    out.append("")

    out.append("// source/Controls.h and Controls.cpp: the option counts and lists.")
    out.extend(assignments("CONTROLS_H", js_scalars(controls_h, "int", "CONTROLS_H")))
    for js, fn in (("FILM_NAMES", "FilmName"), ("MODE_NAMES", "ModeName"), ("SPREAD_NAMES", "SpreadName")):
        out.append(f"const {js} = [" + ", ".join(f"'{n}'" for n in names_of(controls_cpp, fn)) + "];")
    out.append("")
    out.append(END)
    return "\n".join(out)


def region(js):
    start = js.find(BEGIN)
    stop = js.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(END)


def main():
    text = block()
    if "--print" in sys.argv:
        print(text)
        return 0
    with open(PLUGIN_JS) as handle:
        js = handle.read()
    where = region(js)
    if where is None:
        raise SystemExit("demo/plugin.js has no generated block (the BEGIN/END GENERATED lines)")
    updated = js[: where[0]] + text + js[where[1]:]
    if updated == js:
        print("demo/plugin.js already matches the plugin's sources")
        return 0
    with open(PLUGIN_JS, "w") as handle:
        handle.write(updated)
    print("demo/plugin.js: generated block rewritten from source/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
